--- 

# ansible-galaxy install -r requirements.yml
#
collections:
  - name: community.general 
  - name: community.crypto
  - name: ansible.posix
  - name: ansible.utils

roles:
  - src: https://github.com/ehf/fetch-auth-data.git
    version: main
    name: fetch-auth-data

  - src: https://github.com/ehf/deploy-auth-data.git
    version: main
    name: deploy-auth-data

  - src: https://github.com/ehf/dist-totp-data.git
    version: main
    name: dist-totp-data
